repo:
  scanPath: /srv/git
  readme:
    - readme
    - README
    - readme.md
    - README.md
  mainBranch:
    - master
    - main
dirs:
  templates: ./templates
  static: ./static
meta:
  title: legitrx
  description: Runxi Yu's git server thing
server:
  name: git.runxiyu.org
  host: 127.0.0.1
  port: 5555
